name: Trigger Jenkins Pipeline
on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Trigger Jenkins Build
        env:
          JENKINS_USER: jpapadem
          JENKINS_TOKEN: 11e4a4fb90eddbdeef7f24ed4cfe835924
          JENKINS_URL: "https://yellow-turkeys-turn.loca.lt"
          JOB_NAME: "job1"
        run: |
          # Check Jenkins connection
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -k "${JENKINS_URL}/api/json")
          if [ "$RESPONSE" != "200" ]; then
            echo "Cannot connect to Jenkins server"
            exit 1
          fi

          # Try to trigger the job directly
          RESPONSE=$(curl -s -k -X POST -u ${JENKINS_USER}:${JENKINS_TOKEN} "${JENKINS_URL}/job/${JOB_NAME}/build?token=${JENKINS_TOKEN}")
          if [ $? -ne 0 ]; then
            echo "Failed to trigger Jenkins job directly"
            exit 1
          fi

          # Wait for build completion
          for i in {1..12}; do
            echo "Checking build status..."
            BUILD_STATUS=$(curl -s -k -u ${JENKINS_USER}:${JENKINS_TOKEN} "${JENKINS_URL}/job/${JOB_NAME}/lastBuild/api/json")
            
            if [ "$(echo "$BUILD_STATUS" | jq -r '.building')" == "false" ]; then
              RESULT=$(echo "$BUILD_STATUS" | jq -r '.result')
              if [ "$RESULT" == "SUCCESS" ]; then
                echo "Build completed successfully!"
                exit 0
              else
                echo "Build failed with result: $RESULT"
                exit 1
              fi
            fi

            echo "Waiting 5 seconds..."
            sleep 5
          done

          echo "Build did not complete within the timeout period"
          exit 1
